### ISSUE TITLE
Change module path to `github.com/ethereum-optimism/op-geth`

### ISSUE THREAD

**Issue by ale-coinbase** [ethereum-optimism/op-geth#131]
# Rationale

The module path for op-geth is still `github.com/ethereum/go-ethereum` such that any golang project hoping to use both the geth client and the op-geth client will experience a module path collision. 

https://github.com/ethereum-optimism/op-geth/blob/3cea832f24c3e40fbc00786a8acfb3ef14d9a8f8/go.mod#L1

# Implementation

Change module path to `github.com/ethereum-optimism/op-geth`

**Comment by protolambda** [comment]
This is intentional. Changing the module path would cause us to have to change all the import paths as well, requiring a massive diff from upstream geth, and making maintenance tasks of merging and comparing the geth codebases much worse.

The drawback is that this means you cannot use both *as different modules* at the same time, but this also prevents 2 versions of a lot of shared code: `common`, `core`, `types`, `beacon`, etc. and a lot of EVM and bindings, etc. code that would not otherwise work with external go-ethereum libraries.
This way the whole Go ecosystem doesn't have to be forked to work with op-geth (e.g. Go hd-wallet code, EVM utils, tx-fuzzing utils, custom tracers, etc. all just works). And op-geth aims to stay 1:1 compatible with upstream long-term, simply by making all the rollup-functionality opt-in configurable through optional CLI flags and config attributes.

If you are missing an upstream geth feature, then it's time to update op-geth to incorporate that feature; we should be doing more regular merges of the upstream `master` branch into the `optimism` branch of op-geth.


To import it as a library, simply see how the optimism monorepo does it: https://github.com/ethereum-optimism/optimism/blob/develop/go.mod  (the Go `replace` module directive).

Go has this feature where you can pull in a specific repo / module as replacement of the module, solving this exact problem. Note that replacements have to be applied at the end-user `go.mod` level; if you also import the monorepo you will still need the `replace` thing in your `go.mod`.
