### ISSUE TITLE
`LoadOPStackChainConfig`: read `OptimismConfig` from superchain-registry

### ISSUE THREAD

**Issue by geoknee** [ethereum-optimism/op-geth#346]
At the moment, the following fields are neither stored in nor read from the superchain-registry:

https://github.com/ethereum-optimism/op-geth/blob/c6ea6fa09d4e7df6d1ca6b2d32bcb139f021b1e2/params/superchain.go#L76-L79

This means that a chain can omit an **optional*** field such as `OptimismConfig.EIP1559DenominatorCanyon` when starting up "normally", but will have this field overridden if starting us the network cli flags (i.e. via the superchain-registry). 

This ticket also covers adding the fields to the registry here:

https://github.com/ethereum-optimism/superchain-registry/blob/0ef731eae1251994f08107d7aa8b9e492cde7c0a/superchain/superchain.go#L85-L86

---
* we recently made this field optional #345, because chains which did not activate canyon at genesis will not have set it, and we want to maintain backwards compatibility with those chains.

**Comment by protolambda** [comment]
These fields were hardcoded as part of the config/genesis generation, since they are meant to be the same on every standard chain, and thus derived from the configured superchain upgrade time schedule. Since the registry started including more chains, less standard from genesis, customization makes sense. The values should be no-op if the fork is not active, so don't have to be nullable however.
